language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "sudo ./gradlew clean build -x test"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ojs835@naver.com
