server:
  port: 9000

spring:
  application:
    name: study-platform
  datasource:
    platform: mysql
    url: jdbc:mysql://?autoReconnect=true # ??????
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??


