spring:
  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: client id 값
            client-secret: client secret 값
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: callback uri
          github:
            client-id: client id 값
            client-secret: client secret 값
            client-name: Github
            authorization-grant-type: authorization_code
            redirect-uri: callback uri
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token_uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user_name_attribute: id

logging-module:
  version: 0.0.1

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**